### PR TITLE
KHARMA 2024.4

### PR DESCRIPTION
**Pull request by c-prather**
There's been a lot of development hitting dev recently.  KHARMA should probably get a release early this year, which I propose should coincide with the first round of INCITE runs as is tradition.

Highlights:
- First-order flux corrections (FOFC)
- Kastaun robust primitive variable recovery
- Multizone improvements
- Implicit/EMHD bugfixes
- electron temperature tracking fixes and tests
- Upwinded B fluxes
- New reconstruction schemes
- Split/simplified floor injection
- Reconstruction fallback
- Some other stuff from #74
- "Transmitting" polar boundary conditions: correct ghosts and EMFs on polar edges, but no excision

This code is running a bunch of tests pretty nicely on Frontier, so it's well worth pulling & playing with it -- the robust inverter is enabled by default, and `fofc/on=true` will enable FOFC.  Planning to formally release after a few sign-offs, late this week or next week.

### CODE REVIEW

**Comment by c-prather** [comment]
This is ready to release when FOFC is merged today, I'd hope for Friday-ish?  It should get some more tests but I want to freeze what I'm using for INCITE runs.

I'd love if others could confirm their use cases aren't broken, and that the switch to the Kastaun inverter by default hasn't impacted them (except possibly for the better! You can specify `inverter/type=onedw` to compare).  Feel free to also enable FOFC/HLLE and play with that, I've gotten some fantastic results being able to lower floors to sigma=1000+ in MADs and similar fun.  `flag_verbose = 2` will tell you when FOFC is being invoked, for me in 2D it settles from ~50% to 0-1% pretty quickly and stays there -- it also reduces the floor hits to about that level.
SANE in 2D, 256^2 in MKS, HLLE fluxes and S&G'07 CT, scale ranges 1e-6 to ~1e0:
frame_t2995
Only floors needed were 1e-6, 1e-8 on rho, u at the horizon and falling geometrically, as well as at Lorentz factor 50.  These were not often hit -- since FOFC is always applied near/in EH and often along the funnel wall, maybe it's diffusing in material...

**Comment by vedantdhruv96** [comment]
Hi, do you want me to review this PR?

**Comment by c-prather** [comment]
That would be great!

As for releasing though, currently I'm worried about #81 so it may be a bit.  I'd like to verify that any fix works before committing to support the code as it is, since everyone else seems to be running into the issue more than me...

**Comment by vedantdhruv96** [comment]
Sounds good! I thought you were waiting on a required/approving review.
I'll go ahead and approve it and you can merge once it's good to go.

**Review by vedantdhruv96 — APPROVED** [review]

**Comment by c-prather** [comment]
After much faffing about with transmitting polar conditions, I bring you stable (if inaccurate) 90-degree tilts:

https://github.com/AFD-Illinois/kharma/assets/3892634/3f5ed856-76dc-4b1b-aaa5-269f79641ba5

Releasing Friday if nothing comes up. For real this time. For sure.

**Comment by c-prather** [comment]
Releasing.  It's still not impossible to make a run crash, but it's a heck of a lot harder than it used to be.  This version has all the tools we need; getting the runs we want will just be a matter of applying them.

**Pull request merged**
